<?php

$toolbar = new System\Model\Toolbar();
$toolbar->setShowDefaultToolbarActions(true);
$toolbar->setAddCustomToolbarActions(array(
    new System\Model\ToolbarAction('tb_option_refresh', $this->translate("Atualizar"), 'refresh', 'fa-refresh'),
    new System\Model\ToolbarAction('tb_option_config', $this->translate("Configurações"), 'config', 'fa-cog', false)
));
$toolbar->setDisableToolbarActions(array(System\Model\Toolbar::TB_ACTION_PRINT));

$grid = new System\Model\Grid();
$grid->setEntity('Admin\Entity\Country');
$grid->setData($dataGrid);
$panel = new System\Model\Panel('Países', $this->GridHelper($grid));

$view = new System\Model\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);

?>