<div class="row">
  <div class="col-xs-6 col-md-3 manager-link">
    <a href="/manager/banner" class="thumbnail loading">
        <div class="link-content">
            <i class="fa fa-picture-o fa-5x"></i>
            <h3>Banner</h3>
        </div>
    </a>
  </div>

  <div class="col-xs-6 col-md-3 manager-link">
    <a href="/manager/category" class="thumbnail loading">
        <div class="link-content">
            <i class="fa fa-folder-open fa-5x"></i>
            <h3>Categorias</h3>
        </div>
    </a>
  </div>

  <div class="col-xs-6 col-md-3 manager-link">
    <a href="/manager/brand" class="thumbnail loading">
        <div class="link-content">
            <i class="fa fa-tags fa-5x"></i>
            <h3>Marcas</h3>
        </div>
    </a>
  </div>

  <div class="col-xs-6 col-md-3 manager-link">
    <a href="/manager/product" class="thumbnail loading">
        <div class="link-content">
            <i class="fa fa-shopping-cart fa-5x"></i>
            <h3>Produtos</h3>
        </div>
    </a>
  </div>

  <div class="col-xs-6 col-md-3 manager-link">
    <a href="/manager/companymissionview" class="thumbnail loading">
        <div class="link-content">
            <i class="fa fa-history fa-5x"></i>
            <h3>Empresa</h3>
        </div>
    </a>
  </div>

  <div class="col-xs-6 col-md-3 manager-link">
    <a href="/manager/user" class="thumbnail loading">
        <div class="link-content">
            <i class="fa fa-users fa-5x"></i>
            <h3>Usuários</h3>
        </div>
    </a>
  </div>

</div>

