<?php

$toolbar = new \System\Model\Toolbar();
$toolbar->setDisableToolbarActions(array(
    System\Model\Toolbar::TB_ACTION_PRINT,
    System\Model\Toolbar::TB_ACTION_CLONE,
    System\Model\Toolbar::TB_ACTION_UNIFY,
    System\Model\Toolbar::TB_ACTION_SAVE,
));

$multiUpload = new \System\Model\MultiUpload();
$tabs = array(
    new \System\Model\Tab("company", "Arquivos anexados", "", true),
    new \System\Model\Tab("mission", "Upload de arquivos", $this->MultiUploadHelper($multiUpload))
);
$panelContent .= $this->TabHelper($tabs);
$panel = new \System\Model\Panel($caption, $panelContent, 'fa-folder-open');

$view = new \System\Model\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);

?>