<?php

$toolbar = new System\Model\Toolbar();
$toolbar->setShowDefaultToolbarActions(true);
$toolbar->setDisableToolbarActions(array(
    System\Model\Toolbar::TB_ACTION_PRINT,
    System\Model\Toolbar::TB_ACTION_EDIT,
    System\Model\Toolbar::TB_ACTION_SAVE,
    System\Model\Toolbar::TB_ACTION_VIEW,
    System\Model\Toolbar::TB_ACTION_DELETE
));

$grid = new System\Model\Grid();
$grid->setEntity($entity);
$grid->setData($dataGrid);
$panel = new System\Model\Panel($caption, $this->GridHelper($grid), 'fa-folder-open');

$view = new System\Model\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);

?>