<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('categorysave'));

$formCategory = $this->Toolbar(array(
    \Tecnon\View\Toolbar::TB_ACTION_DELETE, 
    \Tecnon\View\Toolbar::TB_ACTION_EDIT, 
    \Tecnon\View\Toolbar::TB_ACTION_PRINT
));

$formCategory .=  "{$this->form()->openTag($form)}
                   {$this->formCollection($form)}
                   {$this->form()->closeTag()}";
              
echo $this->Panel('Nova categoria', $formCategory);

?>

