<?php

$toolbar = new \Admin\Object\Toolbar();
$toolbar->setDisableToolbarActions(array(
    Admin\Object\Toolbar::TB_ACTION_PRINT,
    Admin\Object\Toolbar::TB_ACTION_EDIT,
    Admin\Object\Toolbar::TB_ACTION_DELETE,
    Admin\Object\Toolbar::TB_ACTION_CLONE,
    Admin\Object\Toolbar::TB_ACTION_UNIFY
));

$form = $this->form;
$form->prepare();

$addForm = $this->form()->openTag($form);              
$addForm .= $this->formRow($form->get('title'));
$addForm .= $this->formRow($form->get('send'));
$addForm .= $this->form()->closeTag();
$panel = new \Admin\Object\Panel('Novo país', $addForm);

$view = new \Admin\Object\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);
?>