<?php

$toolbar = new \Admin\Object\Toolbar();
$toolbar->setDisableToolbarActions(array(
    Admin\Object\Toolbar::TB_ACTION_PRINT,
    Admin\Object\Toolbar::TB_ACTION_CLONE,
    Admin\Object\Toolbar::TB_ACTION_UNIFY
));

$form = $this->form;
$form->prepare();

$editForm = $this->form()->openTag($form);              
$editForm .= $this->formCollection($form);
$editForm .= $this->form()->closeTag();
$panel = new \Admin\Object\Panel('Editar país', '');

$view = new \Admin\Object\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);

?>