<?php

$toolbar = new Admin\Object\Toolbar();
$toolbar->setShowDefaultToolbarActions(true);
$toolbar->setAddCustomToolbarActions(array(
    new Admin\Object\ToolbarAction('tb_option_refresh', $this->translate("Refresh"), 'refresh', 'fa-refresh'),
    new Admin\Object\ToolbarAction('tb_option_config', $this->translate("Configurations"), 'config', 'fa-cog', false)
));
$toolbar->setDisableToolbarActions(array(Admin\Object\Toolbar::TB_ACTION_PRINT));

$grid = new Admin\Object\Grid();
$grid->setEntity('Basic\Entity\Country');
$grid->setData($dataGrid);
$panel = new Admin\Object\Panel('Países', $this->GridHelper($grid));

$view = new Admin\Object\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);

?>