<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('countrysave'));

$toolbar = $this->Toolbar(array(
    \Tecnon\View\Toolbar::TB_ACTION_DELETE, 
    \Tecnon\View\Toolbar::TB_ACTION_EDIT, 
    \Tecnon\View\Toolbar::TB_ACTION_PRINT
));

$formContent .= "{$this->form()->openTag($form)}
                 {$this->formCollection($form)}
                 {$this->form()->closeTag()}";
              
echo $this->View('Novo país', $toolbar . $this->Panel($formContent));

?>

