<?php

/**
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url());

$disableOptions = array(
    \Sysma\View\Helper\Toolbar::TB_ACTION_DELETE, 
    \Sysma\View\Helper\Toolbar::TB_ACTION_EDIT, 
    \Sysma\View\Helper\Toolbar::TB_ACTION_PRINT
);

$formContent .= "{$this->form()->openTag($form)}
                 {$this->formCollection($form)}
                 {$this->form()->closeTag()}";

$viewContent = array(
    $this->Toolbar($disableOptions),
    $this->Panel($formContent)
);         
              
echo $this->View('Novo estado', $viewContent);
 * 
 */

?>

