<head>
    <meta charset="utf-8">
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/simple_logo_mini.png'))
                    ->prependStylesheet($this->basePath() . '/css/site.css')
                    ->prependStylesheet($this->basePath() . '/jqTree/jqtree.css')
                    ->prependStylesheet($this->basePath() . '/Choco-Slider-master/estilo.css')
                    ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css');
    ?>
    
    <?php
    echo $this->headScript()
              ->prependFile($this->basePath() . '/Choco-Slider-master/js/jquery.chocoslider.js')
              ->prependFile($this->basePath() . '/jqTree/tree.jquery.js')
              ->prependFile($this->basePath() . '/js/jquery.min.js');
    ?>
    
</head>

<body>
    <?php echo $this->SiteHeaderHelper(); ?>
    <?php echo $this->SiteContentHelper(); ?>
    <?php echo $this->SiteFooterHelper(); ?>
</body>