<head>
    <meta charset="utf-8">
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/site/simple_logo_mini.png'))
                    ->prependStylesheet($this->basePath() . '/css/site.css')
                    ->prependStylesheet($this->basePath() . '/jqTreeView/jquery.treeView.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                    ->prependStylesheet($this->basePath() . '/jssorSlider/css/jssor.css')
                    ->prependStylesheet($this->basePath() . '/highslide/highslide.css')
                    ->prependStylesheet($this->basePath() . '/Choco-Slider-master/estilo.css')
                    ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css');
    ?>
    
    <?php
    echo $this->headScript()
              ->prependFile($this->basePath() . '/Choco-Slider-master/js/jquery.chocoslider.js')
              ->prependFile($this->basePath() . '/jqTreeView/jquery.treeView.js')
              ->prependFile($this->basePath() . '/js/bootstrap.js')
              ->prependFile($this->basePath() . '/js/validateFunctions.js')
              ->prependFile($this->basePath() . '/highslide/highslide.js')
              ->prependFile($this->basePath() . '/jssorSlider/js/jssor.slider.js')
              ->prependFile($this->basePath() . '/jssorSlider/js/jssor.js')
              ->prependFile($this->basePath() . '/js/jquery.min.js');
    ?>
    
</head>

<body>
    <?php echo $this->SiteHeaderHelper(); ?>
    <?php echo $this->SiteContentHelper(); ?>
    <?php echo $this->SiteFooterHelper(); ?>
</body>