<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Dataware'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/simple_logo_mini.png'))
                        ->prependStylesheet($this->basePath() . '/css/DT_bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/system.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/popup-div.css')
                        ->prependStylesheet($this->basePath() . '/css/loading-bar.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/sweetalert-master/lib/sweet-alert.css')
                        ->prependStylesheet($this->basePath() . '/uploadify/css/uploadify.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/DT_bootstrap.js', 'text/javascript')
            ->prependFile($this->basePath() . '/uploadify/swfobject.js', 'text/javascript')
            ->prependFile($this->basePath() . '/uploadify/jquery.uploadify.v2.1.0.min.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/loading-bar.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/popup-div.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.dataTables.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.js', 'text/javascript')
            ->prependFile($this->basePath() . '/jquery-ui/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))            
            ->prependFile($this->basePath() . '/sweetalert-master/lib/sweet-alert.min.js')
        ; ?>

    </head>
    
    <?php echo $this->LoadingHelper();?>
    <?php echo $this->AlertHelper();?>
    
    <body>
        
        <?php echo $this->MenuHelper()?>
        
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        
        <footer>
            <div class="footer">
                <b class="footer-content">
                    <!--<img class='img-logout' src='img/tecnon.png' />-->
                    &copy; 2014 - <?php echo date('Y') ?> por Tecnon - Soluções em sistemas Ltd. <?php echo $this->translate('Todos os direitos reservados.') ?>
                </b>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
