<div class="login" style="width:30%;">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Efetuar login</h3>
        </div>
        <div class="panel-body">

<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('login'));

echo $this->form()->openTag($form);

echo $this->formLabel($form->get('username'));
echo $this->formInput($form->get('username'));
echo $this->formLabel($form->get('password'));
echo $this->formInput($form->get('password'));
echo $this->formElement($form->get('send'));

// echo $this->formCollection($form);

echo $this->formElementErrors($form->get('username'));
echo $this->formElementErrors($form->get('password'));

echo $this->form()->closeTag();

?>

        </div>
    </div>
</div>