<?php

$toolbar = new \System\Model\Toolbar();
$toolbar->setDisableToolbarActions(array(
    System\Model\Toolbar::TB_ACTION_PRINT,
    System\Model\Toolbar::TB_ACTION_EDIT,
    System\Model\Toolbar::TB_ACTION_DELETE,
    System\Model\Toolbar::TB_ACTION_CLONE,
    System\Model\Toolbar::TB_ACTION_UNIFY
));

$form = $this->form;
$form->prepare();

$addForm = $this->form()->openTag($form);              
$addForm .= $this->formCollection($form);
$addForm .= $this->form()->closeTag();
$panel = new \System\Model\Panel('Nova categoria', $addForm, 'fa-folder-open');

$view = new \System\Model\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);
?>