<?php

$toolbar = new \System\Model\Toolbar();
$toolbar->setDisableToolbarActions(array(
    System\Model\Toolbar::TB_ACTION_PRINT,
    System\Model\Toolbar::TB_ACTION_EDIT,
    System\Model\Toolbar::TB_ACTION_DELETE,
    System\Model\Toolbar::TB_ACTION_CLONE,
    System\Model\Toolbar::TB_ACTION_UNIFY
));

$form = $this->form;
$form->prepare();

$addForm = $this->form()->openTag($form);              
$addForm .= $this->formRow($form->get('categoryfather'));
$addForm .= $this->formRow($form->get('title'));
$addForm .= $this->formRow($form->get('cover'));
$addForm .= $this->formRow($form->get('description'));
$addForm .= $this->formRow($form->get('status'));
$addForm .= $this->formRow($form->get('send'));
$addForm .= $this->form()->closeTag();
$panel = new \System\Model\Panel('Novo país', $addForm);

$view = new \System\Model\View();
$view->setToolbar($toolbar);
$view->setPanel($panel);

echo $this->ViewHelper($view);
?>