<div class="destaques">
    <div class="resumo-produto">
        <div class="capa-produto">
            <img src="<?php echo $this->basePath() . '/img/site/produto/1/capa.jpg'; ?>">
        </div>
        <div class="titulo-produto">
            Produto destaque 1
        </div>
        <div class="descricao-produto">
            Esta descricção é um teste, 
            estou escrevendo qualquer coisa aqui, 
            para que tenha uma descrição de exemplo referente ao produto em destaque. 
            Poderão ser escritas diversas coisas para o produto.
        </div>
    </div>
    
    <div class="resumo-produto">
        <div class="capa-produto">
            <img src="<?php echo $this->basePath() . '/img/site/produto/2/capa.jpg'; ?>">
        </div>
        <div class="titulo-produto">
            Produto destaque 2
        </div>
        <div class="descricao-produto">
            Esta descricção é um teste, 
            estou escrevendo qualquer coisa aqui, 
            para que tenha uma descrição de exemplo referente ao produto em destaque. 
            Poderão ser escritas diversas coisas para o produto.
        </div>
    </div>
    
    <div class="resumo-produto">
        <div class="capa-produto">
            <img src="<?php echo $this->basePath() . '/img/site/produto/3/capa.jpg'; ?>">
        </div>
        <div class="titulo-produto">
            Produto destaque 3
        </div>
        <div class="descricao-produto">
            Esta descricção é um teste, 
            estou escrevendo qualquer coisa aqui, 
            para que tenha uma descrição de exemplo referente ao produto em destaque. 
            Poderão ser escritas diversas coisas para o produto.
        </div>
    </div>
    
    <div class="resumo-produto">
        <div class="capa-produto">
            <img src="<?php echo $this->basePath() . '/img/site/produto/4/capa.jpg'; ?>">
        </div>
        <div class="titulo-produto">
            Produto destaque 4
        </div>
        <div class="descricao-produto">
            Esta descricção é um teste, 
            estou escrevendo qualquer coisa aqui, 
            para que tenha uma descrição de exemplo referente ao produto em destaque. 
            Poderão ser escritas diversas coisas para o produto.
        </div>
    </div>
</div>