<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('login'));

$formLogin = $this->form()->openTag($form);              
$formLogin .= $this->formCollection($form);
$formLogin .= $this->form()->closeTag();

$panel = new \System\Model\Panel('Efetuar login', $formLogin, 'fa-user', 'width: 30%; margin-top: 5%; float: center !important');
echo $this->PanelHelper($panel);

?>